### ISSUE TITLE
Support `structlog`

### ISSUE THREAD

**Issue by ddorian** [etianen/logot#108]
Does it support structlog?

**Comment by etianen** [comment]
Not _yet_, but it's on my list of things to add for v1.1.

3rd-party logging integrations have to be added as a new `Capturer` integration (see `loguru` as an example):

https://github.com/etianen/logot/blob/main/logot/_loguru.py

I'd happily accept a PR for this feature, and any other 3rd party integrations. Otherwise, hold tight, and it will arrive in a week or so.

**Comment by etianen** [comment]
@will-ockmore - You mentioned you were keen to add this too.

**Comment by etianen** [comment]
`structlog` support would get pretty powerful once #25 lands too

**Comment by etianen** [comment]
See https://github.com/hynek/structlog/issues/596 for discussion
